# -*- coding: utf-8 -*-
"""Elevvo Task 2: Customer Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VQE-tACMLDthjOuoFpZLWNPPz5XOY0o6

**Task 2: Customer Segmentation**
"""

# import the dependencies
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# loading the data from csv file to a Pandas DataFrame
customer_data = pd.read_csv('/content/Mall_Customers.csv')

# print the five first rows
customer_data.head()

# print information about the data
customer_data.info()

# check for missing values
customer_data.isnull().sum()

# Keep only income and spending score
x_col, y_col = "Annual Income (k$)", "Spending Score (1-100)"
df = customer_data[[x_col, y_col]].dropna()

print(df)

# scaling features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df.values)

print(X_scaled)

# visual exploration of groupings
plt.figure(figsize=(10, 6))
plt.scatter(df[x_col], df[y_col], s=50, alpha=0.7)
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.title('Annual income vs Spending score')
plt.show()

# apply K-Means & determine optimal k (elbow)
ks = list(range(1, 11))
inertias = []

for k in ks:
    # Why: explicit n_init for consistent results across sklearn versions.
    try:
        km = KMeans(n_clusters=k, random_state=42, n_init="auto")
    except TypeError:
        km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_scaled)
    inertias.append(km.inertia_)

# Plot elbow curve
plt.figure(figsize=(6,5))
plt.plot(ks, inertias, marker="o")
plt.title("Elbow graph (Inertia vs k)")
plt.xlabel("k"); plt.ylabel("Inertia")
plt.xticks(ks)
plt.tight_layout(); plt.show()

"""Optimum number of clusters = 5"""

# train the KMeans cluster model
kmeans = KMeans(n_clusters=5, init='k-means++', random_state=42)

# return a label for each data point based on their cluster
Y = kmeans.fit_predict(df)
print(Y)

# visualizing clusters using 2D plots (income vs spending)

# infer the two feature names (expects your df has the two columns you clustered on)
x_col, y_col = df.columns[:2]

centers = kmeans.cluster_centers_

plt.figure(figsize=(6, 5))
for c in np.unique(Y):
    mask = (Y == c)
    plt.scatter(df.loc[mask, x_col], df.loc[mask, y_col], s=25, alpha=0.85, label=f"Cluster {c}")

# centroids in original units since you fit on df directly
plt.scatter(centers[:, 0], centers[:, 1], marker="X", s=200, edgecolor="k")  # why: highlight centers

plt.title("K-Means Clusters (k=5)")
plt.xlabel(x_col)
plt.ylabel(y_col)
plt.legend(title="Cluster")
plt.tight_layout()
plt.show()